language: php

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - make test
